AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Podcast Voice Tool - AWS Native (Polly + Translate)

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12

Resources:
  PodcastFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: podcast-voice-tool
      Handler: lambda_function.lambda_handler
      CodeUri: lambda/
      MemorySize: 256
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - polly:SynthesizeSpeech
                - translate:TranslateText
              Resource: '*'
      Events:
        GenerateAudio:
          Type: Api
          Properties:
            Path: /generate
            Method: post
            RestApiId: !Ref PodcastApi
        Preflight:
          Type: Api
          Properties:
            Path: /generate
            Method: options
            RestApiId: !Ref PodcastApi

  PodcastApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${PodcastApi}.execute-api.${AWS::Region}.amazonaws.com/prod/generate"
